"""
ingest_data.py – Standalone script to ingest medical documents into the
MedicalDocument table with vector embeddings generated by Ollama.

Supports .txt, .md, .pdf, and .csv files via LangChain document loaders.

Usage (from the backend/ directory):
    python -m app.scripts.ingest_data --dir app/data/

Prerequisites:
    1. Ollama must be running locally (`ollama serve`).
    2. Pull the embedding model once:  `ollama pull nomic-embed-text`
    3. The PostgreSQL container must be up (`docker compose up -d`).
"""

import argparse
import asyncio
import logging
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Ensure the `backend/` directory is on sys.path so that `app.*` imports work
# when running the script directly.
# ---------------------------------------------------------------------------
_BACKEND_DIR = str(Path(__file__).resolve().parents[2])
if _BACKEND_DIR not in sys.path:
    sys.path.insert(0, _BACKEND_DIR)

from app.services.ingestion_service import (  # noqa: E402
    SUPPORTED_EXTENSIONS,
    ingest_directory,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


async def _main(directory: str) -> None:
    dir_path = Path(directory)
    if not dir_path.exists():
        print(f"ERROR: Directory not found – {dir_path}")
        sys.exit(1)
    if not dir_path.is_dir():
        print(f"ERROR: Path is not a directory – {dir_path}")
        sys.exit(1)

    files = [
        f for f in dir_path.iterdir()
        if f.is_file() and f.suffix.lower() in SUPPORTED_EXTENSIONS
    ]

    if not files:
        print(f"No supported files found in {dir_path}")
        print(f"  Supported extensions: {', '.join(sorted(SUPPORTED_EXTENSIONS))}")
        return

    print(f"Ingesting {len(files)} file(s) from {dir_path.resolve()}\n")
    processed, total_chunks = await ingest_directory(dir_path)
    print(f"Done ✓  {processed}/{len(files)} file(s) ingested, {total_chunks} total chunk(s) saved.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Ingest medical documents from a directory into the vector database.",
    )
    parser.add_argument(
        "--dir",
        required=True,
        help="Directory containing .txt, .md, .pdf, or .csv files to ingest.",
    )
    args = parser.parse_args()
    asyncio.run(_main(args.dir))


if __name__ == "__main__":
    main()
