import logging

from fastapi import APIRouter, Depends, WebSocket, WebSocketDisconnect
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db, SessionLocal
from app.services.ai_service import generate_medical_response_stream

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    message: str
    conversationHistory: list[dict] = []


class ChatResponse(BaseModel):
    response: str
    severity: str


# ---------------------------------------------------------------------------
# POST /chat/ – synchronous-style JSON reply (consumed by the current
# React frontend via fetch()).
# ---------------------------------------------------------------------------
@router.post("/", response_model=ChatResponse)
async def chat_endpoint(
    request: ChatRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Accept a user message, run the full RAG pipeline, and return the
    complete response as JSON.  Severity is always 'low' for now; a
    future iteration can classify the medical urgency.
    """
    chunks: list[str] = []
    async for token in generate_medical_response_stream(request.message, db):
        chunks.append(token)

    full_response = "".join(chunks)
    return ChatResponse(response=full_response, severity="low")


# ---------------------------------------------------------------------------
# WebSocket /chat/ws – real-time streaming
# ---------------------------------------------------------------------------
@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    Stream RAG response tokens to the client over a WebSocket.

    The client sends a plain-text message; the server streams back
    individual text tokens as they are generated by the LLM, then
    sends a final "[DONE]" sentinel so the client knows the response
    is complete.
    """
    await websocket.accept()

    # Open a dedicated DB session for the lifetime of this connection
    async with SessionLocal() as db:
        try:
            while True:
                user_message = await websocket.receive_text()

                async for token in generate_medical_response_stream(
                    user_message, db
                ):
                    await websocket.send_text(token)

                # Signal that the full response has been sent
                await websocket.send_text("[DONE]")

        except WebSocketDisconnect:
            logger.info("WebSocket client disconnected.")