"""initial schema

Revision ID: a04b7d9195c6
Revises: 
Create Date: 2026-04-17 20:52:57.490035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04b7d9195c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('medical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('specialists', sa.Column('distance', sa.String(), nullable=False))
    op.add_column('specialists', sa.Column('accepts_insurance', sa.Boolean(), nullable=False))
    op.add_column('specialists', sa.Column('urgency_level', sa.String(), nullable=False))
    op.alter_column('specialists', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('specialists', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('specialists', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('specialists', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('specialists', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('specialists', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('specialists', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('specialists', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('specialists', 'urgency_level')
    op.drop_column('specialists', 'accepts_insurance')
    op.drop_column('specialists', 'distance')
    op.drop_table('medical_documents')
    # ### end Alembic commands ###
